"""Persistence boundary for multi-invoice batch facts."""

from typing import Protocol


class InvoiceBatchRepository(Protocol):
    async def create(self, tenant_id: str, key: str, actor_id: str) -> str: ...
    async def list_recent(self, tenant_id: str, actor_id: str, limit: int) -> list[dict]: ...
    async def attach_file(self, batch_id: str, tenant_id: str,
                          document_id: str, filename: str | None) -> str: ...
    async def submit(self, batch_id: str, tenant_id: str, revision: int) -> None: ...
    async def get(self, batch_id: str, tenant_id: str) -> dict: ...
    async def claim(self, lease_seconds: int = 900) -> dict | None: ...
    async def renew(self, claim: dict, lease_seconds: int = 900) -> bool: ...
    async def propose(self, claim: dict, page_count: int,
                      groups: list[dict], uncertain: bool) -> None: ...
    async def fail_claim(self, claim: dict, code: str) -> None: ...
    async def confirm(self, batch_id: str, file_id: str, tenant_id: str,
                      revision: int, page_count: int, groups: list[dict]) -> None: ...
    async def prepare_items(self, batch_id: str, tenant_id: str) -> list[dict] | None: ...
    async def ready_batches(self) -> list[tuple[str, str]]: ...
    async def set_item(self, item_id: str, tenant_id: str,
                       document_id: str, run_id: str | None,
                       derived_pages: list[dict[str, int]]) -> None: ...
    async def source_for_child(self, document_id: str, tenant_id: str) -> dict | None: ...
    async def retry_item(self, batch_id: str, item_id: str, tenant_id: str,
                         expected_run_id: str, key: str) -> None: ...
