events {}
http {
  server {
    listen 8443 ssl;
    ssl_certificate /etc/nginx/certs/tls.crt;
    ssl_certificate_key /etc/nginx/certs/tls.key;
    location /api/ { proxy_pass http://api:8000; }
    location /realms/ { proxy_pass http://keycloak:8080; }
  }
}
