FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlex/paddlex:paddlex3.3.11-paddlepaddle3.2.0-gpu-cuda12.6-cudnn9.5

RUN python -m pip install --no-cache-dir "paddlex[ocr,serving]==3.7.2" "paddleocr==3.7.0"
